# kubectl apply -f duban-salas-35-secret-fe.yml
# Codificar en base64: echo -n "valor" | base64
# Decodificar: echo "dmFsb3I=" | base64 --decode
apiVersion: v1
kind: Secret
metadata:
  name: duban-salas-35-secret-fe
  namespace: duban-salas-35-namespace-fe
type: Opaque
data:
  # VITE_API_URL=http://<IP-BACKEND>:30001
  VITE_API_URL: aHR0cDovL2xvY2FsaG9zdDozMDAwMQ==
